name: 📐 Check Infrastructure as Code (IaC)

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  workflow_dispatch:

permissions: read-all

jobs:
  terraform:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 📑 Check Terraform format
        run: terraform fmt -diff -check -recursive .

      - name: ⚙️ Setup Tflint
        uses: terraform-linters/setup-tflint@v4

      - name: 🔎 Run Tflint
        run: tflint --recursive --format compact --disable-rule terraform_module_pinned_source --minimum-failure-severity=warning